<option value="5"></option>
<option value="6">Padang Panjang</option>
<option value="7">BTG Tabik</option>
<option value="8"></option>
<option value="9"></option>
<option value="10">RAGE</option>
<option value="11"></option>
<option value="12"></option>
<option value="13"></option>
<option value="14"></option>
<option value="15"></option>
<option value="16">T</option>
<option value="17"></option>
<option value="18"></option>
<option value="19"></option>
<option value="20"></option>
<option value="21"></option>
<option value="22"></option>
<option value="23"></option>
<option value="24"></option>
<option value="25"></option>
<option value="26">Mustika 2</option>
<option value="27"></option>
<option value="28">BB</option>
<option value="29">TT</option>
<option value="30">Batu Labi</option>
<option value="31">BGS</option>
<option value="32">Talaweh</option>
<option value="33">KTB</option>
<option value="34">LL/IBB</option>
<option value="35">Bt Nan Gadang</option>
<option value="36">Zipur</option>
<option value="37">Akasia</option>
<option value="38">Zamrud</option>